name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: todo-api
      DOCKER_TAG: latest

    steps:
    # 1️⃣ Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # 2️⃣ Set up Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    # 3️⃣ Install dependencies
    - name: Install dependencies
      run: npm ci

    # 4️⃣ Run tests (optional)
    - name: Run tests
      run: npm test || echo "No tests defined"

    # 5️⃣ Build Docker image
    - name: Build Docker image
      run: docker build -t $DOCKER_IMAGE .

    # 6️⃣ Run Trivy vulnerability scan
    - name: Trivy Scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: $DOCKER_IMAGE:$DOCKER_TAG
        severity: CRITICAL,HIGH
        ignore-unfixed: true

    # 7️⃣ SonarQube Code Quality Scan
    - name: SonarQube Scan
      uses: SonarSource/sonarcloud-github-action@master
      with:
        projectBaseDir: .
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: https://sonarcloud.io

    # 8️⃣ Log in to DockerHub
    - name: DockerHub Login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 9️⃣ Tag & Push Docker image
    - name: Tag Docker image
      run: docker tag $DOCKER_IMAGE:$DOCKER_TAG abhishek8056/$DOCKER_IMAGE:$DOCKER_TAG

    - name: Push Docker image
      run: docker push abhishek8056/$DOCKER_IMAGE:$DOCKER_TAG

