name: DevSecOps CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: echo "No tests yet"

    - name: Build Docker image
      run: docker build -t todo-api .

    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: todo-api:latest

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Tag Docker image
      run: docker tag todo-api:latest abhishek8056/todo-api:latest

    - name: Push Docker image
      run: docker push abhishek8056/todo-api:latest
